#!/bin/sh
# Rebuild assets/docgen/document-kit.js — the self-contained kit the `document`
# tool runs on the managed bun runtime — from assets/docgen/kit.js,
# assets/docgen/rules.json and the versions pinned in assets/docgen/package.json
# (locked by bun.lock).
#
# Run from anywhere; needs the managed bun on PATH (or BUN=<path>). The built
# file is committed, so this only runs when kit.js, rules.json or a pinned
# dependency changes.
set -eu
cd "$(dirname "$0")"
BUN="${BUN:-bun}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cp kit.js rules.json package.json bun.lock "$work"/
(cd "$work" && "$BUN" install --frozen-lockfile --no-summary)
(cd "$work" && "$BUN" build kit.js --target=bun --outfile=document-kit.js)

versions="$("$BUN" -e 'const p=require("./package.json"); console.log(Object.entries(p.dependencies).map(([k, v]) => k + "@" + v).join(", "));')"
# The bundle's header carries the hash of the four sources it was built from,
# so a test can tell a committed bundle from one whose source has moved on
# without it (see src/docgen.rs). Both sides hash the files concatenated in the
# order below.
if command -v sha256sum >/dev/null 2>&1; then
  hash_cmd="sha256sum"
else
  hash_cmd="shasum -a 256"
fi
sources_hash="$(cat kit.js rules.json package.json bun.lock | $hash_cmd | cut -d' ' -f1)"
{
  printf '// Generated by assets/docgen/build.sh with bun %s — do not edit by hand.\n' "$("$BUN" --version)"
  printf '// Sources: %s (see assets/docgen/package.json and bun.lock).\n' "$versions"
  printf '// Sources sha256: %s (kit.js + rules.json + package.json + bun.lock, in that order).\n' "$sources_hash"
  cat "$work/document-kit.js"
} > document-kit.js.new
mv document-kit.js.new document-kit.js
